--inner join
SELECT ORDER_.COFFEE_CODE , COFFEE_NAME, PRICE, ORDER_NUMBER, QUANTITY
FROM ORDER_ INNER JOIN MENU ON
ORDER_.COFFEE_CODE = MENU.COFFEE_CODE;


--RIGHT OUTER JOIN
SELECT C.CUSTOMER_NAME, OR.ORDER_ID, OR.ORDER_NUMBER, OR.QUANTITY, C.CUSTOMER_ADDRESS
FROM CUSTOMER C RIGHT OUTER JOIN ORDER_ OR ON
OR.CUSTOMER_ID = C.CUSTOMER_ID


--LEFT OUTER JOIN
SELECT PAY.TRANSATION_ID , OR.CUSTOMER_ID, OR.ORDER_NUMBER, PAY.PAYMENT_TYPE, PAY.PAYMENT_DATE
FROM ORDER_ OR LEFT OUTER JOIN PAYMENT_METHOD PAY ON
OR.ORDER_ID = PAY.ORDER_ID

--FULL OUTER JOIN
SELECT CUSTOMER.CUSTOMER_NAME, CUSTOMER.CUSTOMER_ADDRESS, CUSTOMER.CUSTOMER_PHONE, PAYMEN_METHOD.PAYMENT_TYPE, PAYMENT_METHOD.PAYMENT_DATE
FROM CUSTOMER FULL OUTER JOIN PAYMENT_METHOD ON 
CUSTOMER.CUSTOMER_ID = PAYMENT_METHOD.CUSTOMER_ID


--NATURAL JOIN
SELECT MENU.COFFEE_NAME , MENU.PRICE, ORDER_.ORDER_NUMBER, ORDER_CUSTOMER_ID
FROM MENU NATURAL JOIN ORDER_ 
WHERE ORDER_.ORDER_ID = MENU.ORDER_ID;


