SELECT X.CUSTOMER_NAME , X.CUSTOMER_ADDRESS, Y.ORDER_ID, Y.COFFEE_CODE, Y.QUANTITY
FROM CUSTOMER X , ORDER_ Y 
WHERE Y.QUANTITY > 1 AND X.CUSTOMER_ID = Y.CUSTOMER_ID;


SELECT X.CUSTOMER_NAME , X.CUSTOMER_ADDRESS, Y.TRANSACTION_ID, Y.PAYMENT_DATE, Y.PAYMENT_TYPE
FROM CUSTOMER X , PAYMENT_METHOD Y 
WHERE Y.PAYMENT_TYPE = 'CASH' AND X.CUSTOMER_ID = Y.CUSTOMER_ID;



CREATE VIEW PAYMENT AS
SELECT TRANSACTION_ID, PAYMENT_TYPE, PAYMENT_DATE
FROM PAYMENT_METHOD
WHERE PAYMENT_TYPE = 'BKASH';



SELECT * FROM PAYMENT;


INSERT INTO PAYMENT VALUES('20200000071', 'CASH', '09-APR-22');


UPDATE PAYMENT
SET PAYMENT_TYPE = 'BKASH'
WHERE TRANSACTION_ID = '20200000071';


CREATE VIEW ORDER_INFO AS
SELECT ORDER_ID, ORDER_NUMBER, COFFEE_CODE, QUANTITY,CUSTOMER_NAME, CUSTOMER_ADDRESS
FROM ORDER_ , CUSTOMER;
