--tuple variables

SELECT X.CUSTOMER_NAME , X.CUSTOMER_ADDRESS, Y.ORDER_ID, Y.COFFEE_CODE, Y.QUANTITY
FROM CUSTOMER X , ORDER_ Y 
WHERE Y.QUANTITY > 1 AND X.CUSTOMER_ID = Y.CUSTOMER_ID;


SELECT X.CUSTOMER_NAME , X.CUSTOMER_ADDRESS, Y.TRANSACTION_ID, Y.PAYMENT_DATE, Y.PAYMENT_TYPE
FROM CUSTOMER X , PAYMENT_METHOD Y 
WHERE Y.PAYMENT_TYPE = 'CASH' AND X.CUSTOMER_ID = Y.CUSTOMER_ID;
